/* PULIRA · copy de ventas por producto. Se fusiona con el catálogo en la tienda (no toca los números del motor).
   beneficio = promesa corta y medible · corto = 1–2 frases que venden · paraQuien = a quién le habla ·
   resultados = qué vas a notar y cuándo (honesto) · contra = por qué a este precio (con datos reales de Mercado Libre, sep-2026). */
var COPY = {
  'esponjas-x4': { beneficio: 'Base pareja sin desperdiciar producto', corto: 'Catorce esponjas en tres tamaños que crecen con agua y dejan la base como segunda piel, con estuche para que se guarden limpias.', paraQuien: 'Para quien se maquilla a diario y está cansada de esponjas que huelen a los quince días.', resultados: 'Desde la primera aplicación: menos producto absorbido y acabado más parejo. Cámbialas cada tres meses: con catorce tienes para un año.', contra: 'Los packs con estuche van de $64 a $119 en Mercado Libre; aquí llegan con garantía y cambio en 30 días.' },
  'mascara-led': { beneficio: 'Piel más luminosa en 8 semanas', corto: 'Luz roja y azul de potencia real. Diez minutos al día sobre la piel limpia y en ocho semanas se nota en luminosidad y textura.', paraQuien: 'Para quien quiere resultados de cabina sin cita y sin pagar cada sesión.', resultados: 'Semanas 1 a 3: piel más descansada. Semanas 8 a 12: luminosidad y textura más pareja. Pide constancia: 4 a 5 veces por semana.', contra: 'Una máscara premium con base cuesta $1,349 en Mercado Libre y una sesión de luz LED en cabina se paga cada vez. Esta es tuya.' },
  'microcorriente': { beneficio: 'Rostro tonificado en 5 minutos', corto: 'Microcorriente que tonifica pómulo y mandíbula. Cinco minutos con gel y el efecto lifting dura horas: ideal antes de un evento.', paraQuien: 'Para quien quiere definir el rostro sin agujas ni procedimientos.', resultados: 'Inmediato: rostro más despierto por unas horas. Con uso diario durante 4 a 6 semanas el efecto se sostiene más. Si lo dejas, se va.', contra: 'Skindion cobra entre $1,499 y $2,200 por un dispositivo equivalente. Aquí, $749, con garantía de 12 meses.' },
  'espatula-ultrasonica': { beneficio: 'Poros limpios de verdad, sin apretar', corto: 'Vibración ultrasónica que desprende del poro lo que el jabón deja. Dos minutos, agua y acero: la limpieza profunda de un facial, cada semana.', paraQuien: 'Para piel mixta o grasa, y para quien ya probó de todo contra los puntos negros.', resultados: 'Desde la primera vez: piel más lisa al tacto. Poros visiblemente más limpios con uso semanal durante un mes.', contra: 'Un facial de limpieza profunda cuesta lo que la espátula y hay que repetirlo cada mes.' },
  'cepillo-facial': { beneficio: 'Limpieza a fondo en un minuto', corto: 'Silicón que no guarda bacterias y vibración sónica en tres velocidades. Un minuto en la regadera y la piel queda limpia sin tallar.', paraQuien: 'Para quien se lava la cara a las prisas y quiere que cuente.', resultados: 'Desde el primer uso: sensación de piel más limpia. En 2 a 4 semanas, menos brillo y maquillaje que asienta mejor.', contra: 'El equivalente de marca premium cuesta de $719 a $3,679. Este, $399.' },
  'removedor-puntos': { beneficio: 'Puntos negros fuera, sin dejar marcas', corto: 'Succión regulable en cuatro niveles con seis cabezales y pantalla LCD. Después del vapor, tres segundos por zona y listo.', paraQuien: 'Para nariz y barbilla con puntos negros persistentes, en piel normal a grasa.', resultados: 'En una sesión ves lo que saca. Úsalo una vez por semana; si abusas, deja moretones.', contra: 'El más vendido de la categoría cuesta $260; este trae seis cabezales y pantalla, con garantía de 12 meses.' },
  'vaporizador': { beneficio: 'Abre el poro en 30 segundos', corto: 'Vapor nano-iónico que abre el poro antes de limpiar y deja la piel lista para el sérum. Tanque de 160 ml, tres niveles y apagado automático.', paraQuien: 'Para quien hace limpieza en casa y quiere el paso que hace que lo demás funcione.', resultados: 'Inmediato: piel más suave y receptiva. Con la espátula o el removedor, la limpieza rinde el doble.', contra: 'Los dos vaporizadores más vendidos de Mercado Libre cuestan $939 y $999.' },
  'gua-sha-electrico': { beneficio: 'Desinflama y relaja en 5 minutos', corto: 'La forma del gua sha, inalámbrico, con calor infrarrojo y nueve velocidades. Cinco minutos por lado con aceite y el rostro amanece desinflamado.', paraQuien: 'Para quien amanece hinchada o pasa el día frente a la pantalla con la mandíbula tensa.', resultados: 'Inmediato: menos hinchazón y tensión. No afila el mentón: desinflama.', contra: 'El gua sha eléctrico de marca cuesta $587; el manual no calienta ni vibra.' },
  'cepillo-secador': { beneficio: 'Seco y con forma en un solo paso', corto: 'Seca y peina al mismo tiempo, con aire frío para fijar. Sin plancha, sin brazo cansado, en la mitad del tiempo.', paraQuien: 'Para cabello medio a largo que quiere volumen y puntas hacia adentro sin ir al salón.', resultados: 'Desde el primer secado. Con los iones negativos, menos frizz que con secador y cepillo por separado.', contra: 'Conair lo vende a $799 y Revlon de $749 a $1,499. Este, $599, con iones y apagado automático.' },
  'masajeador-cabelludo': { beneficio: 'El shampoo por fin llega a la raíz', corto: 'Cabezales de silicón que amasan el cuero cabelludo con velocidad regulable. Relaja, activa la circulación y reparte el producto donde debe.', paraQuien: 'Para quien usa tratamientos de raíz o simplemente quiere cinco minutos de spa antes de lavarse el pelo.', resultados: 'Inmediato: relajación y cuero cabelludo más limpio. No hace crecer el pelo: prepara el terreno para lo que sí.', contra: 'Los importados de marca van de $258 a $500.' },
  'lampara-unas': { beneficio: 'Gel curado en 30 segundos, sin ardor', corto: '48 W nominales con sensor de mano, cuatro temporizadores y modo baja temperatura. Manicure de gel en casa que dura tres semanas.', paraQuien: 'Para quien se hace las uñas en casa o quiere dejar de pagar el salón cada quincena.', resultados: 'Desde la primera manicure: gel curado parejo, sin burbujas ni ardor.', contra: 'Una manicure de gel en salón cuesta más que la lámpara y se repite cada tres semanas.' },
  'espejo-led': { beneficio: 'Luz de día para maquillarte donde sea', corto: 'Luz LED regulable al tacto, aumento 2×, 3× y 10× para el detalle y se pliega. Con pilas o cable: el espejo del tocador que también viaja.', paraQuien: 'Para quien se maquilla con la luz del baño y llega a la calle con otra cara.', resultados: 'Inmediato: ves el color real de la base y de las cejas antes de salir.', contra: 'Los espejos con luz de 8 pulgadas van de $383 a $555; los de 20× de marca, $590. Este, $449 con garantía.' },
  'limpiador-brochas': { beneficio: 'Brochas limpias y secas en un minuto', corto: 'Gira la brocha en agua con jabón neutro y la seca al aire en segundos. Adaptadores de silicón para casi cualquier mango.', paraQuien: 'Para quien tiene más de cinco brochas y las lava menos de lo que debería.', resultados: 'Desde el primer lavado: brochas sin residuo y sin olor. Menos bacterias en la cara, menos brotes.', contra: 'Los limpiadores con secado cuestan hasta $712.' },
  'kit-rutina': { beneficio: 'La limpieza completa, en una caja', corto: 'Cepillo sónico para el día a día, espátula ultrasónica para la limpieza profunda semanal y el pack de esponjas para aplicar. Llega en paquetes separados.', paraQuien: 'Para empezar una rutina en serio sin comprar pieza por pieza.', resultados: 'Semana 1: piel más limpia. Mes 1: poros más limpios y maquillaje que asienta mejor.', contra: 'Cuesta menos que las tres piezas sueltas y el envío va gratis.' },
  'kit-glow': { beneficio: 'Luz y tono: la rutina de cabina', corto: 'La máscara LED trabaja la piel y la microcorriente trabaja el músculo. Quince minutos, cuatro veces por semana. Llega en dos paquetes.', paraQuien: 'Para quien quiere el resultado de dos tratamientos de cabina, en casa y para siempre.', resultados: 'Inmediato: rostro más despierto. Semanas 8 a 12: luminosidad y textura más pareja.', contra: 'Cuesta menos que las dos piezas sueltas y el envío va gratis.' },
  'kit-cabello': { beneficio: 'Lavar, estimular, secar con forma', corto: 'Masajeador de cuero cabelludo y cepillo secador para salir con forma. El salón, en dos aparatos. Llega en dos paquetes.', paraQuien: 'Para quien quiere volumen y cuero cabelludo sano sin salón.', resultados: 'Desde el primer uso: secado en la mitad del tiempo y menos frizz.', contra: 'Cuesta menos que las dos piezas sueltas.' }
};
